# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌘ + ⇧ Shift Key Modifier {{{

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;10u"
key = "Back"
mods = "Command|Shift"


# }}}





# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEYS {{{
###########################
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "`kg"
# key = "g"
# mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`L"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`S"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`n"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`p"
key = "{"
mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "LBracket"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002&"
# key = "RBracket"
# mods = "Command|Shift"



# }}}

# OTHER KEYS {{{
###########################



# }}}

# }}}


# }}}
#######################################################################


