
#######################################################################
# ⌘ Command Key {{{
#######################################################################

# Shift + Option Key Modifier {{{
# ⌘ + ⇧ + ⌥
################################################

###########################
# NUMBER KEYS {{{
###########################




# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEY {{{
###########################




# }}}

###########################
# FN KEYS {{{
###########################




# }}}

###########################
# OTHER KEYS {{{
###########################


# }}}


# }}}


# }}}
#######################################################################


