# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command-option.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command+Option key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌥ Option Key Modifier {{{
# ⌘ + ⌥
################################################

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;11u"
key = "Back"
mods = "Command|Alt"


# }}}





# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEYS {{{
###########################




# }}}

###########################
# FN KEYS {{{
###########################




# }}}

###########################
# OTHER KEYS {{{
###########################



# }}}

# }}}


# }}}
#######################################################################


