
#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌥ Option Key Modifier {{{
# ⌘ + ⌥
################################################

###########################
# NUMBER KEYS {{{
###########################




# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEYS {{{
###########################




# }}}

###########################
# FN KEYS {{{
###########################




# }}}

###########################
# OTHER KEYS {{{
###########################



# }}}

# }}}


# }}}
#######################################################################


