# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌘ + ⇧ Shift Key Modifier {{{

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;10u"
key = "Back"
mods = "Command|Shift"


# }}}

# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEYS {{{
###########################


# A-Z {{{

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "`kg"
# key = "g"
# mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`L"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`S"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`n"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "`p"
key = "{"
mods = "Command|Shift"


# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

[[keyboard.bindings]]
chars = "\u001B[13;10u"
key = "Return"
mods = "Command|Shift"

# }}}

# Home Row + 1: Brackets, Backslash {{{

# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "LBracket"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002&"
# key = "RBracket"
# mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001b[124;10u"
key = "|"
mods = "Command|Shift"



# }}}


# }}}

# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;10u"
key = "Escape"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[32;10u"
key = "Space"
mods = "Command|Shift"

# }}}

# }}}


# }}}
#######################################################################


