# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command-option-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command+Option+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# Shift + Option Key Modifier {{{
# ⌘ + ⇧ + ⌥
################################################

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;14u"
key = "Back"
mods = "Command|Shift|Alt"


# }}}





# }}}

###########################
# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEY {{{
###########################


# A-Z {{{


# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

[[keyboard.bindings]]
chars = "\u001B[13;14u"
key = "Return"
mods = "Command|Shift|Alt"

# }}}

# Home Row + 1: Brackets, Backslash {{{

[[keyboard.bindings]]
chars = "\u001b[123;14u"
key = "{"
mods = "Command|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001b[125;14u"
key = "}"
mods = "Command|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001b[124;14u"
key = "|"
mods = "Command|Shift|Alt"


# }}}


# }}}

# FN KEYS {{{
###########################




# }}}


# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;14u"
key = "Escape"
mods = "Command|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001B[32;14u"
key = "Space"
mods = "Command|Shift|Alt"

# }}}


# }}}


# }}}
#######################################################################


