# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command-option.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command+Option key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌥ Option Key Modifier {{{
# ⌘ + ⌥
################################################

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;11u"
key = "Back"
mods = "Command|Alt"


# }}}


# }}}

# ARROW KEYS {{{
###########################




# }}}

###########################
# REGULAR KEYS {{{
###########################


# A-Z {{{


# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

[[keyboard.bindings]]
chars = "\u001B[13;11u"
key = "Return"
mods = "Command"

# }}}

# Home Row + 1: Brackets, Backslash {{{

[[keyboard.bindings]]
chars = "\u001b[91;11u"
key = "LBracket"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001b[93;11u"
key = "RBracket"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B[92;11u"
key = "Backslash"
mods = "Command|Alt"

# }}}


# }}}

# FN KEYS {{{
###########################




# }}}


# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;11u"
key = "Escape"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B[32;11u"
key = "Space"
mods = "Command|Alt"

# }}}

# }}}


# }}}
#######################################################################


