# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/command.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Command key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌘ Command Key {{{
#######################################################################

# ⌘ Pure Bindings (No Modifiers) {{{

# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################

[[keyboard.bindings]]
chars = "`-"
key = "Minus"
mods = "Command"

# Emulate C-S-BS
[[keyboard.bindings]]
# chars = "\u001b[127;9u"
chars = "\u001b[127;6u"
key = "Back"
mods = "Command"

# }}}


# Emulate C-S-1
[[keyboard.bindings]]
# chars = "`1"
# chars = "\u001B[27;5;49~"
chars = "\u001b[33;5u"
key = "Key1"
mods = "Command"

# Emulate C-S-2
[[keyboard.bindings]]
# chars = "`2"
# chars = "\u001B[27;5;50~"
chars = "\u001b[64;5u"
key = "Key2"
mods = "Command"

# Emulate C-S-3
[[keyboard.bindings]]
# chars = "`3"
# chars = "\u001B[27;5;51~"
chars = "\u001b[35;5u"
key = "Key3"
mods = "Command"

# Emulate C-S-4
[[keyboard.bindings]]
# chars = "`4"
# chars = "\u001B[27;5;52~"
chars = "\u001b[36;5u"
key = "Key4"
mods = "Command"

# Emulate C-S-5
[[keyboard.bindings]]
# chars = "`5"
# chars = "\u001B[27;5;53~"
chars = "\u001b[37;5u"
key = "Key5"
mods = "Command"

# Emulate C-S-6
[[keyboard.bindings]]
# chars = "`6"
# chars = "\u001B[27;5;54~"
chars = "\u001b[64;5u"
key = "Key6"
mods = "Command"

# Emulate C-S-7
[[keyboard.bindings]]
# chars = "`7"
# chars = "\u001B[27;5;55~"
chars = "\u001b[38;5u"
key = "Key7"
mods = "Command"

# Emulate C-S-8
[[keyboard.bindings]]
# chars = "`8"
# chars = "\u001B[27;5;56~"
chars = "\u001b[42;5u"
key = "Key8"
mods = "Command"

# Emulate C-S-9
[[keyboard.bindings]]
# chars = "`9"
# chars = "\u001B[27;5;57~"
chars = "\u001b[40;5u"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;48~"
key = "Key0"
mods = "Command"



# }}}

# ARROW KEYS {{{
###########################
[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Command"

# }}}

# REGULAR KEYS {{{
###########################

# A-Z {{{

# Emulate C-S-A
[[keyboard.bindings]]
chars = "\u001B[65;5u"
key = "A"
mods = "Command"

# Emulate C-S-B
[[keyboard.bindings]]
# chars = "`="
chars = "\u001B[66;5u"
key = "B"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

# Emulate C-S-D
[[keyboard.bindings]]
chars = "`d"
# chars = "\u001B[68;5u"
key = "D"
mods = "Command"

# Emulate C-S-E
[[keyboard.bindings]]
chars = "\u001B[69;5u"
key = "E"
mods = "Command"

# Emulate C-S-F
[[keyboard.bindings]]
chars = "\u001B[70;5u"
key = "F"
mods = "Command"

# Emulate C-S-G
[[keyboard.bindings]]
# chars = "`g"
chars = "\u001B[71;5u"
# chars = "\u001B[103;6u"
key = "G"
mods = "Command"

# Emulate C-S-H
[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Command"

# Emulate C-S-I
[[keyboard.bindings]]
chars = "\u001b[73;5u"
key = "I"
mods = "Command"

# Emulate C-S-J
[[keyboard.bindings]]
chars = "\u001b[74;5u"
key = "J"
mods = "Command"

# Emulate C-S-K
[[keyboard.bindings]]
chars = "\u001b[75;5u"
key = "K"
mods = "Command"

# Emulate C-S-L
[[keyboard.bindings]]
# chars = "`l"
chars = "\u001b[76;5u"
key = "L"
mods = "Command"

# Emulate C-S-M
[[keyboard.bindings]]
# chars = "`k"
chars = "\u001b[77;5u"
key = "M"
mods = "Command"

# Emulate C-S-N
[[keyboard.bindings]]
# chars = "`n"
chars = "\u001B[78;5u"
key = "N"
mods = "Command"

# Emulate C-S-O
[[keyboard.bindings]]
chars = "\u001B[79;5u"
key = "O"
mods = "Command"

# Emulate C-S-P
[[keyboard.bindings]]
chars = "\u001B[80;5u"
key = "P"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

# Emulate C-S-R
[[keyboard.bindings]]
chars = "\u001B[82;5u"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "`s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "`c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "`C"
key = "T"
mods = "Command|Shift"

# Emulate C-S-U
[[keyboard.bindings]]
chars = "\u001B[85;5u"
key = "U"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

# Emulate C-S-W
[[keyboard.bindings]]
# chars = "`W"
chars = "\u001B[87;5u"
key = "W"
mods = "Command"

# Emulate C-S-X
[[keyboard.bindings]]
# chars = "`-"
chars = "\u001B[88;5u"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "`X"
key = "X"
mods = "Command|Shift"

# Emulate C-S-Y
[[keyboard.bindings]]
# chars = ",tc"
chars = "\u001B[89;5u"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "`z"
key = "Z"
mods = "Command"


# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

# Switch Pane
[[keyboard.bindings]]
chars = "`;"
key = "Semicolon"
mods = "Command"

# Emulate C-S-Return
[[keyboard.bindings]]
# chars = "\u001B[13;5u"
chars = "\u001b[13;6u"
key = "Return"
mods = "Command"

# }}}


# }}}

# Home Row + 1: Brackets, Backslash {{{

[[keyboard.bindings]]
chars = "`["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "`]"
key = "RBracket"
mods = "Command"

# New Vertical Split
[[keyboard.bindings]]
chars = "\u001B[92;9u"
key = "Backslash"
mods = "Command"


# }}}


# FN KEYS {{{
###########################
[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Command"

# Emulate S-F10
[[keyboard.bindings]]
# chars = "\u001B[21;3~"
chars = "\u001B[21;2~"
key = "F10"
mods = "Command"

# Emulate S-F11
[[keyboard.bindings]]
# chars = "\u001B[23;3~"
chars = "\u001B[23;2~"
key = "F11"
mods = "Command"

# Emulate S-F12
[[keyboard.bindings]]
chars = "\u001B[24;2~"
# chars = "\u001B[24;3~"
key = "F12"
mods = "Command"
# }}}


# Bottom Row: Comma, Period, Slash {{{
########################
[[keyboard.bindings]]
chars = "\u001B[60;5u"
key = "Comma"
mods = "Command"

# Relieve Cmd+l
[[keyboard.bindings]]
# chars = "\u001B[62;5u"
chars = "`l"
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[63;5u"
key = "Slash"
mods = "Command"


# }}}

# Other Keys: Escape, Tab, Space {{{

# Currently: S-F11 to exit Nested Mode
[[keyboard.bindings]]
# chars = "\u001b[27;9u"
chars = "\u001B[23;2~"
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[32;9u"
key = "Space"
mods = "Command"

# }}}

# }}}

# }}}
#######################################################################


