# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/control-option.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Control+Option key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌃ Control Key {{{
#######################################################################

# ⌃ + ⌥ Option Key Modifier {{{

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;7u"
key = "Back"
mods = "Control|Alt"


# }}}



# }}}

###########################
# ARROW KEYS {{{
###########################



# }}}

###########################
# REGULAR KEYS {{{
###########################

# A-Z {{{

# Added 2026-03-28 from jceb

[[keyboard.bindings]]
chars = "\u001B[97;7u"
key = "A"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[98;7u"
key = "B"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[99;7u"
key = "C"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[100;7u"
key = "D"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[101;7u"
key = "E"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[102;7u"
key = "F"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[103;7u"
key = "G"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[104;7u"
key = "H"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[105;7u"
key = "I"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[106;7u"
key = "J"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[107;7u"
key = "K"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[108;7u"
key = "L"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[109;7u"
key = "M"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[110;7u"
key = "N"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[111;7u"
key = "O"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[112;7u"
key = "P"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[113;7u"
key = "Q"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[114;7u"
key = "R"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[115;7u"
key = "S"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[116;7u"
key = "T"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[117;7u"
key = "U"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[118;7u"
key = "V"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[119;7u"
key = "W"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[120;7u"
key = "X"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[121;7u"
key = "Y"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001B[122;7u"
key = "Z"
mods = "Alt|Control"







# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

[[keyboard.bindings]]
chars = "\u001b[13;7u"
key = "Return"
mods = "Control|Option"


# }}}

# Home Row + 1: Brackets, Backslash {{{

[[keyboard.bindings]]
chars = "\u001b[91;7u"
key = "LBracket"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001b[93;7u"
key = "RBracket"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[92;7u"
key = "Backslash"
mods = "Control|Alt"

# }}}



# }}}

# FN KEYS {{{



# }}}


# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;7u"
key = "Escape"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001B[32;7u"
key = "Space"
mods = "Control|Alt"

# }}}

# }}}


# }}}
#######################################################################



