# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/control-option-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Control+Option+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌃ Control Key {{{
#######################################################################

# ⌃ + ⇧ + ⌥ Shift + Option Key Modifier {{{

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;8u"
key = "Back"
mods = "Control|Shift|Alt"


# }}}

# }}}

# ARROW KEYS {{{



# }}}

# REGULAR KEYS {{{


# A-Z {{{


# }}}

# Bottom Row: Comma, Period, Slash {{{


# }}}

# Home Row: Semicolon, Quotes, Return {{{

[[keyboard.bindings]]
chars = "\u001b[13;8u"
key = "Return"
mods = "Control|Shift|Alt"

# }}}

# Home Row + 1: Brackets, Backslash {{{

[[keyboard.bindings]]
chars = "\u001b[123;8u"
key = "{"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001b[125;8u"
key = "}"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001b[124;8u"
key = "|"
mods = "Control|Shift|Alt"

# }}}


# }}}

# FN KEYS {{{



# }}}

# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;8u"
key = "Escape"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
chars = "\u001B[32;8u"
key = "Space"
mods = "Control|Shift|Alt"

# }}}

# }}}


# }}}
#######################################################################



