# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/control-option-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Control+Option+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌃ Control Key {{{
#######################################################################

# ⌃ + ⇧ + ⌥ Shift + Option Key Modifier {{{

###########################
# NUMBER KEYS {{{
###########################

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;8u"
key = "Back"
mods = "Control|Shift|Alt"


# }}}




# }}}

###########################
# ARROW KEYS {{{
###########################



# }}}

###########################
# REGULAR KEYS {{{
###########################



# }}}

###########################
# FN KEYS {{{
###########################



# }}}

###########################
# OTHER KEYS {{{
###########################



# }}}

# }}}


# }}}
#######################################################################



