# custom_cursor_colors = true
# tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = true

[font]
# AppleFontSmoothing = true
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
