# vim: set filetype=tmux fdm=marker foldenable foldlevel=4 nospell:
# File:          config/option-shift.toml
# Author:        Mark van der Meulen <mark@vdm.id.au>
# Description:   Option+Shift key bindings for Alacritty
# Last Modified: 2025-08-06


#######################################################################
# ⌥ Option Key {{{
#######################################################################

# ⌥ + ⇧ Shift Key Modifier {{{
################################################

# NUMBER KEYS {{{

# Number Row: Backtick, Minus, Equals, Backspace {{{
########################
[[keyboard.bindings]]
chars = "\u001b[127;4u"
key = "Back"
mods = "Alt|Shift"


# }}}


[[keyboard.bindings]]
chars = "\u001B!"
key = "Key1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B@"
key = "Key2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B$"
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B&"
key = "Key7"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B("
key = "Key9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B)"
key = "Key0"
mods = "Alt|Shift"

# Number Row: Backtick, Minus, Equals, Delete {{{
########################
[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B+"
key = "Equals"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001b[127;4u"
key = "Back"
mods = "Alt|Shift"

# }}}

# }}}

# REGULAR KEYS {{{

# A-Z {{{
########################
[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

# }}}

# Bottom Row: Comma, Period, Slash {{{
########################
[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B?"
key = "Slash"
mods = "Alt|Shift"

# }}}

# Home Row: Semicolon, Quotes, NOTE: NO Return {{{
########################
[[keyboard.bindings]]
chars = "\u001B:"
key = "Semicolon"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\""
key = "\""
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[13;4u"
key = "Return"
mods = "Alt|Shift"

# }}}

# Home Row + 1: Brackets, Backslash {{{
########################
[[keyboard.bindings]]
chars = "\u001B{"
key = "LBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B}"
key = "RBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

# }}}

# }}}


# Other Keys: Escape, Tab, Space {{{

[[keyboard.bindings]]
chars = "\u001b[27;4u"
key = "Escape"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[32;4u"
key = "Space"
mods = "Alt|Shift"

# }}}

################################################

# }}}


# }}}
