
#######################################################################
# ⌥ Option Key {{{
#######################################################################

# ⌥ Pure Bindings (No Modifiers) {{{

# NUMBER KEYS {{{

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

# Number Row: Backtick, Minus, Equals, Delete {{{
########################
[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B="
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001b[127;3u"
# chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

# }}}

# }}}

# ARROW KEYS {{{

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[5;3~"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[6;3~"
key = "PageDown"
mods = "Alt"



# }}}

# REGULAR KEYS {{{

# A-Z {{{
########################
[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

# }}}

# Bottom Row: Comma, Period, Slash {{{
########################
[[keyboard.bindings]]
chars = "\u001B,"
# chars = "\u0018\u0010"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Alt"

# }}}

# Home Row: Semicolon, Quotes, Return {{{
########################
[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B'"
key = "'"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Alt"

# }}}

# Home Row + 1: Brackets, Backslash {{{
########################
[[keyboard.bindings]]
chars = "\u001B["
# chars = "\u0018["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
# chars = "\u0018]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

# }}}

# }}}

# FN KEYS {{{

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"


# }}}

# OTHER KEYS {{{

[[keyboard.bindings]]
chars = "\u001B "
key = "Space"
mods = "Alt"

# Shows as ^X^A in cat -v
[[keyboard.bindings]]
chars = "\u0018\u0001"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Alt"
chars = "\u001b[1;3H"

[[keyboard.bindings]]
key = "End"
mods = "Alt"
chars = "\u001b[1;3F"

# }}}

# }}}

# }}}
