
#######################################################################
# ⇧ Shift Key {{{
#######################################################################

# ARROW KEYS {{{
###########################
[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"


# }}}

# FN KEYS {{{
###########################
[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"
# }}}

# OTHER KEYS {{{
###########################
[[keyboard.bindings]]
chars = "\u001b[127;2u"
key = "Back"
mods = "Shift"

# This key code is confirmed here: https://powerusers.codidact.com/posts/291531
[[keyboard.bindings]]
chars = "\u001B[13;2u"
# chars = "\u001B[27~"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[32;2u"
# chars = "\u001B[30~"
key = "Space"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001b[27;2u"
key = "Escape"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"
# }}}

# }}}
#######################################################################


